export const AUTHENTICATING = "AUTHENTICATING";
export const UNAUTHENTICATING = "UNAUTHENTICATING";
export const GETTING_OAUTH_REQUEST_TOKEN = "GETTING_OAUTH_REQUEST_TOKEN";
export const GETTING_OAUTH_ACCESS_TOKEN = "GETTING_OAUTH_ACCESS_TOKEN";
export const FETCHING_POSTS = "FETCHING_POSTS";
